# Generated by Django 5.2.3 on 2025-06-12 01:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3aec7c52-2ffe-4470-980e-2f65ffa51cc7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
